// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiuswurlkovxhajecwog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpdXN3dXJsa292eGhhamVjd29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjAyNjgsImV4cCI6MjA2MDI5NjI2OH0.1fvlqX1RPBfXRwEsslMoYzTlFaicEU2TqumtyNc7Jqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);